const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
}[character]));

function renderAdminLogin(csrfToken, errorMessage = '') {
    return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Admin sign in | Sanzida's Closet</title><link rel="stylesheet" href="/assets/css/site.css"></head><body class="admin-auth-page"><main class="admin-auth-card"><p class="eyebrow">Private workspace</p><h1>Admin<br><em>sign in.</em></h1>${errorMessage ? `<div class="alert alert--soft" role="alert">${escapeHtml(errorMessage)}</div>` : ''}<form class="auth-form" method="post"><input type="hidden" name="csrf_token" value="${escapeHtml(csrfToken)}"><div class="field"><label class="field__label" for="admin-email">Email</label><input class="input" id="admin-email" name="email" type="email" autocomplete="username" required></div><div class="field"><label class="field__label" for="admin-password">Password</label><input class="input" id="admin-password" name="password" type="password" autocomplete="current-password" required></div><button class="button" type="submit">Enter workspace <span aria-hidden="true">&rarr;</span></button></form></main></body></html>`;
}

function renderAdminDashboard(admin, metrics, csrfToken) {
    const navigation = [['Overview', '/admin/'], ['Products', '/admin/module.php?name=products'], ['Categories', '/admin/module.php?name=categories'], ['Orders', '/admin/module.php?name=orders'], ['Customers', '/admin/module.php?name=customers'], ['Inventory', '/admin/module.php?name=inventory'], ['Coupons', '/admin/module.php?name=coupons'], ['Reviews', '/admin/module.php?name=reviews'], ['Returns', '/admin/module.php?name=returns'], ['Content', '/admin/module.php?name=content'], ['SEO', '/admin/module.php?name=seo'], ['Reports', '/admin/module.php?name=reports'], ['Audit', '/admin/module.php?name=audit'], ['Settings', '/admin/module.php?name=settings']];
    const cards = [['Revenue', `₹ ${Number(metrics.revenue).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`], ['Orders', metrics.orders], ['Customers', metrics.customers], ['Products', metrics.products], ['Open orders', metrics.pending_orders], ['Returns', metrics.returns], ['Refunds', metrics.refunds], ['Low stock', metrics.low_stock]].map(([label, value]) => `<article class="admin-metric"><p class="label">${label}</p><strong>${escapeHtml(value)}</strong></article>`).join('');
    return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Admin dashboard | Sanzida's Closet</title><link rel="stylesheet" href="/assets/css/site.css"></head><body class="admin-page"><aside class="admin-sidebar"><a class="admin-brand" href="/admin/">SC <span>Admin</span></a><nav aria-label="Admin navigation">${navigation.map(([label, href], index) => `<a class="${index === 0 ? 'is-active' : ''}" href="${href}">${label}</a>`).join('')}</nav></aside><main class="admin-main"><header class="admin-topbar"><div><p class="eyebrow">Private workspace</p><h1>Good morning, ${escapeHtml(admin.display_name)}.</h1></div><form method="post" action="/admin/logout.php"><input type="hidden" name="csrf_token" value="${escapeHtml(csrfToken)}"><button class="button button--outline" type="submit">Sign out</button></form></header><section class="admin-metrics" aria-label="Business metrics">${cards}</section></main></body></html>`;
}

function renderAdminModule(admin, moduleName, rows, errorMessage = '', csrfToken = '', successMessage = '') {
    const labels = { products: 'Products', categories: 'Categories', orders: 'Orders', customers: 'Customers', inventory: 'Inventory', coupons: 'Coupons', reviews: 'Reviews', returns: 'Returns', refunds: 'Refunds', content: 'Content', seo: 'SEO', settings: 'Settings', audit: 'Audit logs', reports: 'Reports' };
    const permissions = { products: 'products.manage', categories: 'categories.manage', orders: 'orders.manage', customers: 'customers.manage', inventory: 'inventory.manage', coupons: 'coupons.manage', reviews: 'reviews.manage', returns: 'orders.manage', refunds: 'orders.manage', content: 'content.manage', seo: 'seo.manage', settings: 'settings.manage', audit: 'audit.view', reports: 'reports.view' };
    const navigation = Object.entries(labels).map(([key, label]) => `<a class="${key === moduleName ? 'is-active' : ''}" href="/admin/module.php?name=${key}">${label}</a>`).join('');
    const columns = Object.keys(rows[0] || { status: '' });
    const actionForm = (row) => {
        const id = Number(row.id || 0);
        const form = (action, values, label, extra = '') => `<form class="admin-inline-form" method="post" action="/admin/module.php?name=${moduleName}"><input type="hidden" name="csrf_token" value="${escapeHtml(csrfToken)}"><input type="hidden" name="action" value="${action}"><input type="hidden" name="id" value="${id}">${extra}<label class="sr-only" for="admin-${moduleName}-${id}-${action}">${label}</label><select class="select" id="admin-${moduleName}-${id}-${action}" name="status">${values.map((value) => `<option value="${value}" ${row.status === value ? 'selected' : ''}>${value.replace(/_/g, ' ')}</option>`).join('')}</select><button class="button button--outline" type="submit">${label}</button></form>`;
        if (moduleName === 'orders') return form('status', ['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'completed', 'returned'], 'Update');
        if (moduleName === 'customers') return form('status', ['active', 'inactive', 'suspended'], 'Update');
        if (moduleName === 'reviews') return `${form('moderate', ['pending', 'approved', 'rejected'], 'Moderate')}<form class="admin-inline-form" method="post" action="/admin/module.php?name=reviews"><input type="hidden" name="csrf_token" value="${escapeHtml(csrfToken)}"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="${id}"><button class="button button--outline" type="submit">Delete</button></form>`;
        if (moduleName === 'returns') return form('status', ['requested', 'approved', 'rejected', 'received', 'inspecting', 'refunded', 'exchanged', 'completed', 'cancelled'], 'Update');
        if (moduleName === 'refunds') return form('status', ['pending', 'processed', 'failed', 'cancelled'], 'Update');
        if (moduleName === 'products') return `<form class="admin-inline-form" method="post" action="/admin/module.php?name=products"><input type="hidden" name="csrf_token" value="${escapeHtml(csrfToken)}"><input type="hidden" name="action" value="archive"><input type="hidden" name="id" value="${id}"><button class="button button--outline" type="submit">Archive</button></form>`;
        if (moduleName === 'inventory') return `<form class="admin-inline-form" method="post" action="/admin/module.php?name=inventory"><input type="hidden" name="csrf_token" value="${escapeHtml(csrfToken)}"><input type="hidden" name="action" value="adjust"><input type="hidden" name="variant_id" value="${Number(row.variant_id)}"><label class="sr-only" for="inventory-change-${Number(row.variant_id)}">Quantity adjustment</label><input class="input" id="inventory-change-${Number(row.variant_id)}" name="quantity_change" type="number" step="1" required><button class="button button--outline" type="submit">Adjust</button></form>`;
        return '';
    };
    const tableRows = rows.map((row) => `<tr>${columns.map((column) => `<td>${escapeHtml(row[column] instanceof Date ? row[column].toISOString() : row[column] ?? '—')}</td>`).join('')}<td>${actionForm(row)}</td></tr>`).join('');
    const denied = !['owner', 'super-admin'].includes(admin.role_slug) && !admin.permissions.includes(permissions[moduleName]);
    const content = denied ? '<div class="alert alert--soft" role="alert">You do not have permission to view this module.</div>' : `${errorMessage ? `<div class="alert alert--soft" role="alert">${escapeHtml(errorMessage)}</div>` : ''}${successMessage ? `<div class="alert alert--soft" role="status">${escapeHtml(successMessage)}</div>` : ''}<div class="admin-panel"><div class="admin-table-wrap"><table class="admin-table"><thead><tr>${columns.map((column) => `<th>${escapeHtml(column.replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()))}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${tableRows || `<tr><td colspan="${columns.length + 1}">No records found.</td></tr>`}</tbody></table></div></div>`;
    return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(labels[moduleName])} | Admin</title><link rel="stylesheet" href="/assets/css/site.css"></head><body class="admin-page"><aside class="admin-sidebar"><a class="admin-brand" href="/admin/">SC <span>Admin</span></a><nav aria-label="Admin navigation">${navigation}</nav></aside><main class="admin-main"><header class="admin-topbar"><div><p class="eyebrow">Admin module</p><h1>${escapeHtml(labels[moduleName])}</h1></div><a class="button button--outline" href="/admin/">Overview</a></header>${content}</main></body></html>`;
}

module.exports = { renderAdminDashboard, renderAdminLogin, renderAdminModule };