const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
}[character]));

function shell(title, content) {
    return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(title)} | Sanzida's Closet</title><link rel="stylesheet" href="/assets/css/site.css"></head><body class="checkout-page"><header class="catalogue-header"><a class="brand" href="/"><img class="brand-logo" src="/assets/images/brand-logo.jpg" alt="" width="52" height="52"><span class="brand-name">Sanzida's Closet</span></a><nav class="catalogue-header__nav" aria-label="Catalogue navigation"><a href="/">Home</a><a href="/products/">Shop</a><a href="/categories/">Collections</a><a href="/sale/">Sale</a></nav><div class="catalogue-header__actions"><a class="header-cart-link" href="/cart/">Bag</a></div></header>${content}<footer class="catalogue-footer"><span>&copy; ${new Date().getFullYear()} Sanzida's Closet</span><span>Catalogue powered by the Sanzida's Closet database</span></footer></body></html>`;
}

function renderReturnPolicy(policy) {
    const days = Number(policy?.days_from_delivery || 7);
    const allowed = Array.isArray(policy?.allowed_resolutions) ? policy.allowed_resolutions : ['refund', 'exchange'];
    return shell('Returns & exchanges', `<main class="auth-main"><section class="auth-card auth-card--wide"><p class="eyebrow">Customer care</p><h1>Returns &amp;<br><em>exchanges.</em></h1><div class="alert alert--soft" role="status">We want every order to feel right. You can request a return or exchange within ${days} days of delivery, subject to eligibility.</div><div class="auth-form"><div class="field"><label class="field__label">Return window</label><p class="muted">Items must be returned in their original condition, with tags and packaging intact where applicable.</p></div><div class="field"><label class="field__label">Available resolutions</label><p class="muted">${escapeHtml(allowed.map((value) => value.charAt(0).toUpperCase() + value.slice(1)).join(', '))}</p></div><div class="field"><label class="field__label">How to request</label><p class="muted">Visit your order details, select the item you wish to return, and submit your request. Our team will review it and confirm the next step.</p></div><div class="field"><label class="field__label">Not covered</label><p class="muted">Worn products, damage caused after delivery, or requests outside the eligible window may not qualify.</p></div><div class="form-actions"><a class="button" href="/">Back to home</a><a class="button button--outline" href="/account/">View account</a></div></div></section></main>`);
}

function renderReturnForm(order, policy, csrfToken, errorMessage = '', successMessage = '') {
    let options = '';
    if (order && policy) options = order.items.map((item) => `<option value="${Number(item.id)}">${escapeHtml(item.product_name)} &times; ${Number(item.quantity)}</option>`).join('');
    const resolutions = (policy?.allowed_resolutions || ['refund']).map((value) => `<option value="${escapeHtml(value)}">${escapeHtml(value.replace(/_/g, ' ').replace(/^\w/, (letter) => letter.toUpperCase()))}</option>`).join('');
    const form = successMessage ? `<div class="alert alert--soft" role="status">${escapeHtml(successMessage)}</div><a class="button" href="/account/">Return to your account</a>` : order && policy ? `<p class="auth-card__intro">Choose the piece and tell us what happened. Your request will be reviewed before pickup or refund.</p><form class="auth-form" method="post"><input type="hidden" name="csrf_token" value="${escapeHtml(csrfToken)}"><input type="hidden" name="order" value="${escapeHtml(order.order_number)}"><div class="field"><label class="field__label" for="return-item">Order item</label><select class="select" id="return-item" name="order_item_id" required>${options}</select></div><div class="form-grid"><div class="field"><label class="field__label" for="return-quantity">Quantity</label><input class="input" id="return-quantity" name="quantity" type="number" min="1" value="1" required></div><div class="field"><label class="field__label" for="return-reason">Reason</label><select class="select" id="return-reason" name="reason" required><option value="damaged_item">Damaged item</option><option value="wrong_item">Wrong item</option><option value="missing_item">Missing item</option><option value="changed_mind">Changed my mind</option><option value="defective">Defective</option><option value="other">Other</option></select></div><div class="field"><label class="field__label" for="return-type">Request type</label><select class="select" id="return-type" name="return_type"><option value="return">Return</option><option value="exchange">Exchange</option></select></div><div class="field"><label class="field__label" for="return-resolution">Resolution</label><select class="select" id="return-resolution" name="resolution" required>${resolutions}</select></div></div><div class="field"><label class="field__label" for="return-note">Additional details</label><textarea class="textarea" id="return-note" name="note" maxlength="4000"></textarea></div><button class="button" type="submit">Submit request <span aria-hidden="true">&rarr;</span></button></form>` : '<div class="alert alert--soft" role="alert">Order not found or unavailable.</div>';
    return shell('Request return', `<main class="auth-main"><section class="auth-card auth-card--wide"><p class="eyebrow">Aftercare</p><h1>Request a<br><em>return.</em></h1>${errorMessage ? `<div class="alert alert--soft" role="alert">${escapeHtml(errorMessage)}</div>` : ''}${form}</section></main>`);
}

module.exports = { renderReturnForm, renderReturnPolicy };